dist: xenial
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true
  - bundler: true
  - directories:
    - doc/target

branches:
  only:
    - master

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      sudo: required
      addons:
        apt:
          packages:
            - libssl-dev
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo clean
        - cargo test
      after_success:
        - rustfmt src/* --write-mode=diff -f
        - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        - USE_SKEPTIC=1 cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --all-features

    - rust: beta
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo clean
        - cargo test -j6
      after_success:
        - rustfmt src/* --write-mode=diff -f

    - rust: nightly
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo clean
        - cargo test -j6
      after_success:
        - rustfmt src/* --write-mode=diff -f

    - rust: stable
      script:
        - cargo clean
        - cargo doc --no-deps
        - rm -f target/doc/.lock
